// 손쉽게 http 요청을 받아볼 수 있음
// post는 브라우저를 통해 테스트하기 힘드니 intellij의 기능을 이용하기
// ### 요청의 이름
### get account
GET http://localhost:8080/account?user_id=1
Accept: application/json

### create account
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 12345
}

### delete account
DELETE http://localhost:8080/account
Content-Type: application/json

{
"userId": 1,
"accountNumber": "1000000000"
}