### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 30000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "221212b3bf2a488280cb21115c91257e",
  "accountNumber": "1000000000",
  "amount": 30000
}

### query transaction
GET http://localhost:8080/transaction/e88b61466b474652af298d04c41cd9e6